### PR TITLE
fix: update linkbutton to match figma design

### LINKED ISSUE #936: Reconcile button and linkbutton component
The LinkButton and Button components have different design. Either Button should support A-tag or LinkButton should match the API of Button. I think we should have LinkButton and Button use the same code internally, but expose different Components.

Image

### PR DESCRIPTION
**Pull request by mikaelbr**
Fixes https://github.com/varianter/variant.no/issues/936
Matching button design with component in Figma. And supporting normal link strings.

## Todo later

- Should support all types of icons
- Follow up on some inconsistencies with secondary and background (hover, active etc) that doesn't follow design a cross different views in Figma

## Screenshots

Screenshot 2024-12-06 at 19 26 07
Screenshot 2024-12-06 at 19 26 04
Screenshot 2024-12-06 at 19 25 56

### CODE REVIEW

File: src/components/navigation/header/Header.tsx [hunk 1]
```diff
@@ -102,9 +101,16 @@ export const Header = ({
                     pathTranslations={pathTranslations}
                   />
                 )}
-                <Button size="large" type="secondary" background="light">
-                  <Text type="labelLarge">{t("contact_us")}</Text>
-                </Button>
+
+                {/* THIS SHOULD BE MOVED TO SANITY */}
```
Comment (anemne) [inline src/components/navigation/header/Header.tsx]: We could possibly use the contact email field under Admin --> Parent Company

**Review by anemne — APPROVED** [review]
lgtm 😎

File: src/components/navigation/header/Header.tsx (hunk 1 above)
Comment (mikaelbr) [reply src/components/navigation/header/Header.tsx]: Should have been separate PR but fixed it here to sneak it in
